services:
  # TODO: add wings and pterodactyl
  ctrlpanel_development:
    build:
      context: ../../
      dockerfile: ./docker/standalone/Dockerfile
    container_name: ctrlpanel_development
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - '../..:/var/www/html:rw'
      - './nginx_config:/etc/nginx/conf.d/:rw'
    networks:
      - ctrlpanel

  mysql:
    image: mysql
    container_name: ctrlpanel_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ctrlpanel
      MYSQL_USER: ctrlpaneluser
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./mysql:/var/lib/mysql:delegated"
    networks:
      - ctrlpanel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ctrlpanel_phpmyadmin
    depends_on:
      - mysql
    ports:
      - '8080:80'
    environment:
      - PMA_HOST=ctrlpanel_mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_ARBITRARY=1
    networks:
      - ctrlpanel

  redis:
    image: redis
    container_name: ctrlpanel_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - ctrlpanel

networks:
  ctrlpanel:
