blank_issues_enabled: true
contact_links:
  - name: 🤷 Installation Help
    url: https://discord.gg/4Y6HjD2uyU
    about: Please visit our Discord for help with your installation.
  - name: ❓ General Question
    url: https://discord.gg/4Y6HjD2uyU
    about: Please visit our Discord for general questions about the CtrlPanel.
