<?php

namespace App\Exceptions;

class ApiErrorCode
{
    public const MISSING_AUTHORIZATION_HEADER = 'MISSING_AUTHORIZATION_HEADER';
    public const INVALID_TOKEN = 'INVALID_TOKEN';
    public const TOKEN_INACTIVE = 'TOKEN_INACTIVE';
    public const TOKEN_EXPIRED = 'TOKEN_EXPIRED';
    public const INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS';
    public const PERMISSION_ESCALATION = 'PERMISSION_ESCALATION';
    public const RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED';
    public const VALIDATION_ERROR = 'VALIDATION_ERROR';
    public const RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND';
    public const RESOURCE_ALREADY_SUSPENDED = 'RESOURCE_ALREADY_SUSPENDED';
    public const RESOURCE_NOT_SUSPENDED = 'RESOURCE_NOT_SUSPENDED';
    public const PTERODACTYL_ERROR = 'PTERODACTYL_ERROR';
    public const INTERNAL_ERROR = 'INTERNAL_ERROR';
    public const REGENERATION_DENIED = 'REGENERATION_DENIED';
}
